### ISSUE TITLE
Abstract state storage mechanisms

### ISSUE THREAD

**Issue by int00h5525** [dirtbags/moth#108]
- [x] Wrap all state changes/reads into a single place
- [x] Abstract state changes so that, if we wanted to, it would be easy to move from the `state/` directory to something else, like a database

**Comment by nealey** [comment]
We have no need for a relational database. Since the system is architected for a key/value store, something like Redis should work (I haven't messed with Redis much as a developer).

With Redis's `APPEND` operation, we can lose `points.new` and `points.tmp`, which were just filesystem-as-key-value-store hacks anyway. Points log would stay the same.

Team name assignments would stay the same.

That's actually all the persistent storage we need MOTH to write.

Configuration could be stored in Redis too. For the first pass, we could provide an admin tool that reads and writes values, and also does some sanity checking on writes. RFC3339 times could benefit a lot from sanity checks.

So the keys we'd store:

- `points.log` [stream] points log
- `teams` [hash] map of team hash to team name (Redis allows us to add other values later)
- `initialized` [string] remove to re-init
- `messages` (v4) [list or stream] broadcast announcements
- `hours` (v4) [list] operating hours
- `disabled` (v3) [string] create to pause
- `until` (v3) [string] time to pause

**Comment by nealey** [comment]
Man. Because of the way we designed this way back in v1, the state is very well defined, and we don't even need a persistent MOTHd. We could run this in a cloud using FAAS.

**Comment by nealey** [comment]
Okay, I did this in v4.
