### ISSUE TITLE
Track per-team puzzle progress

### ISSUE THREAD

**Issue by int00h5525** [dirtbags/moth#29]
Currently, each team can see all currently-unlocked puzzles, but has no way to easily identify which puzzles their team has completed. Allowing teams to identify which puzzles have and have not been completed, of those currently unlocked, would make it easier for teams to participate without keeping track of progress in a secondary repository.

**Comment by nealey** [comment]
We are going to want to turn this off for certain events where we want to
force teams to develop a tracking system. But for the other events, what
about a scoreboard that just lists out, per team, what point puzzles in
what categories have not been solved by the team?

Something like:

Team A
- cata 10 40 320
- catb 200

Team B
- cata 320
- catb 7 200

Put into the projector rotation, a simple list like this could be very
helpful.

**Comment by cgtboy1988** [comment]
I like the idea.  Because the list can get long with a lot of teams and categories, we may want an auto-scroll feature to go down the list for the projector, and a static version that can be viewed in individual browsers by the teams.

Is just deleting the .html file an acceptable way to handle per-competition scoreboard selection?  As in, if you do not want this view, just delete the .html file (and maybe the .js file so that it cannot easily be replicated)?  Other ways to do this would be to introduce a config file or have moth branches, but these seem more complicated than they are worth unless we have a lot of things to config.

**Comment by cgtboy1988** [comment]
I see the config in being discussed in the Mattermost.  Will look there for guidance.

**Comment by nealey** [comment]
Scoreboard-proj rotation is a good question for a new issue :)

But, briefly, yeah, we should have something listening for a 404 in the iframe, that will trigger loading the next view immediately. Then you can delete views with impunity.

**Comment by nealey** [comment]
LLNL now has a scoreboard that does this, but given feedback at our last event that people thought our server was dumpy because it didn't track scores for them, I have a new idea.

We should provide some sort of button on the puzzles page that highlights unsolved puzzles. Since we're storing the team token in the browser now, we can do this easily enough, by pulling down the points log and filtering by team... although we will have to also tell the browser what their *anonymized* team ID is, probably at registration time, since `points.json` doesn't provide team IDs (for security reasons).

Then, we should provide a way to turn this off, so that pressing the button gives a message like "Disabled for this event to encourage communication between team members".

**Comment by nealey** [comment]
Here is how this is going to work:

Currently in the `devel` branch, there is a half-implemented (and therefore broken, sorry) implementation of a new `/state` endpoint, which combines (among other things) `/points.json` and `puzzle.json`. Because we are requiring a valid Team ID to get puzzles, the client must send the Team ID to this new endpoint. We can now sort out what team you are on when giving you the points log.

In the new `/state` endpoint, if you send a Team ID, then your team's entry in the points log will be for team 0: remember, we enumerate teams in the points log to prevent exposing IDs. If you don't send a Team ID in the request, there won't be a team 0.

This should make front-end work a whole lot easier. Just go through the points log, and every entry for team 0 is a puzzle you mark as solved, or whatever.

**Comment by nealey** [comment]
v4, as part of the points log, now provides a teamID of `0`. So a client could pretty easily be written which lists which puzzles the team has solved. Since it all comes down in one `state` request, this could even be added to the puzzles overview.

**Comment by nealey** [comment]
Server support for this is done. Any further work needs to happen in the client.
